version: "3.8"
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./public/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
    networks:
      - internal

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./public/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
    networks:
      - internal

  mysql:
    container_name: db
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbData:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - internal

networks:
  internal:
    driver: bridge
volumes:
  dbData: